[2025-10-11T14:42:55.470+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-11T14:42:55.482+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cafe_sales_etl.generate_reports manual__2025-10-11T11:42:20.585172+00:00 [queued]>
[2025-10-11T14:42:55.488+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cafe_sales_etl.generate_reports manual__2025-10-11T11:42:20.585172+00:00 [queued]>
[2025-10-11T14:42:55.488+0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-10-11T14:42:55.507+0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_reports> on 2025-10-11 11:42:20.585172+00:00
[2025-10-11T14:42:55.512+0300] {standard_task_runner.py:72} INFO - Started process 61149 to run task
[2025-10-11T14:42:55.515+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'cafe_sales_etl', 'generate_reports', 'manual__2025-10-11T11:42:20.585172+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/cafe_sales_etl_dag.py', '--cfg-path', '/tmp/tmp72cpghyl']
[2025-10-11T14:42:55.516+0300] {standard_task_runner.py:105} INFO - Job 73: Subtask generate_reports
[2025-10-11T14:42:55.559+0300] {task_command.py:467} INFO - Running <TaskInstance: cafe_sales_etl.generate_reports manual__2025-10-11T11:42:20.585172+00:00 [running]> on host archlinux
[2025-10-11T14:42:55.628+0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='cafe_sales_etl' AIRFLOW_CTX_TASK_ID='generate_reports' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T11:42:20.585172+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-11T11:42:20.585172+00:00'
[2025-10-11T14:42:55.629+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-10-11T14:42:55.629+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-10-11T14:42:55.629+0300] {logging_mixin.py:190} INFO - Current task name:generate_reports state:running start_date:2025-10-11 11:42:55.482715+00:00
[2025-10-11T14:42:55.629+0300] {logging_mixin.py:190} INFO - Dag name:cafe_sales_etl and current dag run status:running
[2025-10-11T14:42:55.630+0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-11T14:42:55.644+0300] {logging_mixin.py:190} WARNING - /home/hsooni/cafe_sales_etl/airflow/dags/cafe_sales_etl_dag.py:118 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-10-11T14:42:55.644+0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/airflow/dags/cafe_sales_etl_dag.py", line 118, in run_sql_reports
    df = pd.read_sql_query(text(query), conn)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 526, in read_sql_query
    return pandas_sql.read_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 2738, in read_query
    cursor = self.execute(sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 2670, in execute
    raise TypeError("Query must be a string unless using sqlalchemy.")
TypeError: Query must be a string unless using sqlalchemy.
[2025-10-11T14:42:55.652+0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-10-11T14:42:55.653+0300] {logging_mixin.py:190} INFO - Task start:2025-10-11 11:42:55.482715+00:00 end:2025-10-11 11:42:55.652318+00:00 duration:0.169603
[2025-10-11T14:42:55.653+0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): generate_reports> dag:<DAG: cafe_sales_etl> dagrun:<DagRun cafe_sales_etl @ 2025-10-11 11:42:20.585172+00:00: manual__2025-10-11T11:42:20.585172+00:00, state:running, queued_at: 2025-10-11 11:42:20.600624+00:00. externally triggered: True>
[2025-10-11T14:42:55.653+0300] {logging_mixin.py:190} INFO - Failure caused by Query must be a string unless using sqlalchemy.
[2025-10-11T14:42:55.653+0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=cafe_sales_etl, task_id=generate_reports, run_id=manual__2025-10-11T11:42:20.585172+00:00, execution_date=20251011T114220, start_date=20251011T114255, end_date=20251011T114255
[2025-10-11T14:42:55.672+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-11T14:42:55.673+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 73 for task generate_reports (Query must be a string unless using sqlalchemy.; 61149)
Traceback (most recent call last):
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/airflow/dags/cafe_sales_etl_dag.py", line 118, in run_sql_reports
    df = pd.read_sql_query(text(query), conn)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 526, in read_sql_query
    return pandas_sql.read_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 2738, in read_query
    cursor = self.execute(sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 2670, in execute
    raise TypeError("Query must be a string unless using sqlalchemy.")
TypeError: Query must be a string unless using sqlalchemy.
[2025-10-11T14:42:55.687+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-11T14:42:55.705+0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-11T14:42:55.706+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
