[2025-10-11T14:43:07.550+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-11T14:43:07.562+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cafe_sales_etl.validate_data manual__2025-10-11T11:42:44.112144+00:00 [queued]>
[2025-10-11T14:43:07.568+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cafe_sales_etl.validate_data manual__2025-10-11T11:42:44.112144+00:00 [queued]>
[2025-10-11T14:43:07.568+0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-10-11T14:43:07.588+0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): validate_data> on 2025-10-11 11:42:44.112144+00:00
[2025-10-11T14:43:07.593+0300] {standard_task_runner.py:72} INFO - Started process 61327 to run task
[2025-10-11T14:43:07.596+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'cafe_sales_etl', 'validate_data', 'manual__2025-10-11T11:42:44.112144+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/cafe_sales_etl_dag.py', '--cfg-path', '/tmp/tmp2cdcip2v']
[2025-10-11T14:43:07.597+0300] {standard_task_runner.py:105} INFO - Job 76: Subtask validate_data
[2025-10-11T14:43:07.640+0300] {task_command.py:467} INFO - Running <TaskInstance: cafe_sales_etl.validate_data manual__2025-10-11T11:42:44.112144+00:00 [running]> on host archlinux
[2025-10-11T14:43:07.711+0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='cafe_sales_etl' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T11:42:44.112144+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-11T11:42:44.112144+00:00'
[2025-10-11T14:43:07.712+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-10-11T14:43:07.712+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-10-11T14:43:07.712+0300] {logging_mixin.py:190} INFO - Current task name:validate_data state:running start_date:2025-10-11 11:43:07.562737+00:00
[2025-10-11T14:43:07.712+0300] {logging_mixin.py:190} INFO - Dag name:cafe_sales_etl and current dag run status:running
[2025-10-11T14:43:07.713+0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-11T14:43:07.723+0300] {logging_mixin.py:190} INFO - âœ… Validation passed: 7773 rows, 0 nulls in total_spent.
[2025-10-11T14:43:07.724+0300] {python.py:240} INFO - Done. Returned value was: None
[2025-10-11T14:43:07.729+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-11T14:43:07.729+0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cafe_sales_etl, task_id=validate_data, run_id=manual__2025-10-11T11:42:44.112144+00:00, execution_date=20251011T114244, start_date=20251011T114307, end_date=20251011T114307
[2025-10-11T14:43:07.743+0300] {logging_mixin.py:190} INFO - Task instance in success state
[2025-10-11T14:43:07.743+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-10-11T14:43:07.743+0300] {logging_mixin.py:190} INFO - Dag name:cafe_sales_etl queued_at:2025-10-11 11:42:44.126708+00:00
[2025-10-11T14:43:07.743+0300] {logging_mixin.py:190} INFO - Task hostname:archlinux operator:PythonOperator
[2025-10-11T14:43:07.768+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-11T14:43:07.792+0300] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-11T14:43:07.802+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
