[2025-10-11T14:40:06.997+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-11T14:40:07.008+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cafe_sales_etl.validate_data manual__2025-10-11T11:39:51.686429+00:00 [queued]>
[2025-10-11T14:40:07.014+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cafe_sales_etl.validate_data manual__2025-10-11T11:39:51.686429+00:00 [queued]>
[2025-10-11T14:40:07.014+0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-10-11T14:40:07.033+0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): validate_data> on 2025-10-11 11:39:51.686429+00:00
[2025-10-11T14:40:07.038+0300] {standard_task_runner.py:72} INFO - Started process 59379 to run task
[2025-10-11T14:40:07.041+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'cafe_sales_etl', 'validate_data', 'manual__2025-10-11T11:39:51.686429+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/cafe_sales_etl_dag.py', '--cfg-path', '/tmp/tmpttg2q2nv']
[2025-10-11T14:40:07.042+0300] {standard_task_runner.py:105} INFO - Job 63: Subtask validate_data
[2025-10-11T14:40:07.112+0300] {task_command.py:467} INFO - Running <TaskInstance: cafe_sales_etl.validate_data manual__2025-10-11T11:39:51.686429+00:00 [running]> on host archlinux
[2025-10-11T14:40:07.178+0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='cafe_sales_etl' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T11:39:51.686429+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-11T11:39:51.686429+00:00'
[2025-10-11T14:40:07.179+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-10-11T14:40:07.179+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-10-11T14:40:07.179+0300] {logging_mixin.py:190} INFO - Current task name:validate_data state:running start_date:2025-10-11 11:40:07.008597+00:00
[2025-10-11T14:40:07.180+0300] {logging_mixin.py:190} INFO - Dag name:cafe_sales_etl and current dag run status:running
[2025-10-11T14:40:07.180+0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-11T14:40:07.190+0300] {logging_mixin.py:190} INFO - âœ… Validation passed: 7773 rows, 0 nulls in total_spent.
[2025-10-11T14:40:07.190+0300] {python.py:240} INFO - Done. Returned value was: None
[2025-10-11T14:40:07.195+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-11T14:40:07.195+0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cafe_sales_etl, task_id=validate_data, run_id=manual__2025-10-11T11:39:51.686429+00:00, execution_date=20251011T113951, start_date=20251011T114007, end_date=20251011T114007
[2025-10-11T14:40:07.208+0300] {logging_mixin.py:190} INFO - Task instance in success state
[2025-10-11T14:40:07.209+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-10-11T14:40:07.209+0300] {logging_mixin.py:190} INFO - Dag name:cafe_sales_etl queued_at:2025-10-11 11:39:51.701843+00:00
[2025-10-11T14:40:07.209+0300] {logging_mixin.py:190} INFO - Task hostname:archlinux operator:PythonOperator
[2025-10-11T14:40:07.253+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-11T14:40:07.291+0300] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-11T14:40:07.306+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
