[2025-10-11T14:38:27.161+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-11T14:38:27.172+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cafe_sales_etl.validate_data manual__2025-10-11T11:33:07.358953+00:00 [queued]>
[2025-10-11T14:38:27.178+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cafe_sales_etl.validate_data manual__2025-10-11T11:33:07.358953+00:00 [queued]>
[2025-10-11T14:38:27.178+0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-10-11T14:38:27.196+0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): validate_data> on 2025-10-11 11:33:07.358953+00:00
[2025-10-11T14:38:27.202+0300] {standard_task_runner.py:72} INFO - Started process 58143 to run task
[2025-10-11T14:38:27.205+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'cafe_sales_etl', 'validate_data', 'manual__2025-10-11T11:33:07.358953+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/cafe_sales_etl_dag.py', '--cfg-path', '/tmp/tmp0kpk2_pd']
[2025-10-11T14:38:27.205+0300] {standard_task_runner.py:105} INFO - Job 57: Subtask validate_data
[2025-10-11T14:38:27.250+0300] {task_command.py:467} INFO - Running <TaskInstance: cafe_sales_etl.validate_data manual__2025-10-11T11:33:07.358953+00:00 [running]> on host archlinux
[2025-10-11T14:38:27.314+0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='cafe_sales_etl' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T11:33:07.358953+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-11T11:33:07.358953+00:00'
[2025-10-11T14:38:27.315+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-10-11T14:38:27.315+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-10-11T14:38:27.316+0300] {logging_mixin.py:190} INFO - Current task name:validate_data state:running start_date:2025-10-11 11:38:27.172540+00:00
[2025-10-11T14:38:27.316+0300] {logging_mixin.py:190} INFO - Dag name:cafe_sales_etl and current dag run status:running
[2025-10-11T14:38:27.316+0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-11T14:38:27.327+0300] {logging_mixin.py:190} INFO - âœ… Validation passed: 7773 rows, 0 nulls in total_spent.
[2025-10-11T14:38:27.328+0300] {python.py:240} INFO - Done. Returned value was: None
[2025-10-11T14:38:27.332+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-11T14:38:27.333+0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cafe_sales_etl, task_id=validate_data, run_id=manual__2025-10-11T11:33:07.358953+00:00, execution_date=20251011T113307, start_date=20251011T113827, end_date=20251011T113827
[2025-10-11T14:38:27.347+0300] {logging_mixin.py:190} INFO - Task instance in success state
[2025-10-11T14:38:27.347+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-10-11T14:38:27.348+0300] {logging_mixin.py:190} INFO - Dag name:cafe_sales_etl queued_at:2025-10-11 11:33:07.375096+00:00
[2025-10-11T14:38:27.348+0300] {logging_mixin.py:190} INFO - Task hostname:archlinux operator:PythonOperator
[2025-10-11T14:38:27.377+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-11T14:38:27.401+0300] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-11T14:38:27.414+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
