[2025-10-11T14:37:36.367+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-11T14:37:36.396+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cafe_sales_etl.validate_data manual__2025-10-11T11:32:15.420045+00:00 [queued]>
[2025-10-11T14:37:36.413+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cafe_sales_etl.validate_data manual__2025-10-11T11:32:15.420045+00:00 [queued]>
[2025-10-11T14:37:36.414+0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-10-11T14:37:36.451+0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): validate_data> on 2025-10-11 11:32:15.420045+00:00
[2025-10-11T14:37:36.464+0300] {standard_task_runner.py:72} INFO - Started process 57823 to run task
[2025-10-11T14:37:36.471+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'cafe_sales_etl', 'validate_data', 'manual__2025-10-11T11:32:15.420045+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/cafe_sales_etl_dag.py', '--cfg-path', '/tmp/tmpvcu1bs00']
[2025-10-11T14:37:36.472+0300] {standard_task_runner.py:105} INFO - Job 54: Subtask validate_data
[2025-10-11T14:37:36.532+0300] {task_command.py:467} INFO - Running <TaskInstance: cafe_sales_etl.validate_data manual__2025-10-11T11:32:15.420045+00:00 [running]> on host archlinux
[2025-10-11T14:37:36.647+0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='cafe_sales_etl' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T11:32:15.420045+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-11T11:32:15.420045+00:00'
[2025-10-11T14:37:36.648+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-10-11T14:37:36.648+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-10-11T14:37:36.649+0300] {logging_mixin.py:190} INFO - Current task name:validate_data state:running start_date:2025-10-11 11:37:36.397173+00:00
[2025-10-11T14:37:36.649+0300] {logging_mixin.py:190} INFO - Dag name:cafe_sales_etl and current dag run status:running
[2025-10-11T14:37:36.649+0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-11T14:37:36.665+0300] {logging_mixin.py:190} INFO - âœ… Validation passed: 7773 rows, 0 nulls in total_spent.
[2025-10-11T14:37:36.666+0300] {python.py:240} INFO - Done. Returned value was: None
[2025-10-11T14:37:36.670+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-11T14:37:36.671+0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cafe_sales_etl, task_id=validate_data, run_id=manual__2025-10-11T11:32:15.420045+00:00, execution_date=20251011T113215, start_date=20251011T113736, end_date=20251011T113736
[2025-10-11T14:37:36.685+0300] {logging_mixin.py:190} INFO - Task instance in success state
[2025-10-11T14:37:36.685+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-10-11T14:37:36.685+0300] {logging_mixin.py:190} INFO - Dag name:cafe_sales_etl queued_at:2025-10-11 11:32:15.431733+00:00
[2025-10-11T14:37:36.685+0300] {logging_mixin.py:190} INFO - Task hostname:archlinux operator:PythonOperator
[2025-10-11T14:37:36.723+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-11T14:37:36.745+0300] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-11T14:37:36.758+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
