[2025-10-11T14:37:40.072+0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-11T14:37:40.083+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cafe_sales_etl.generate_reports manual__2025-10-11T11:32:15.420045+00:00 [queued]>
[2025-10-11T14:37:40.089+0300] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cafe_sales_etl.generate_reports manual__2025-10-11T11:32:15.420045+00:00 [queued]>
[2025-10-11T14:37:40.089+0300] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-10-11T14:37:40.116+0300] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): generate_reports> on 2025-10-11 11:32:15.420045+00:00
[2025-10-11T14:37:40.121+0300] {standard_task_runner.py:72} INFO - Started process 57862 to run task
[2025-10-11T14:37:40.124+0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'cafe_sales_etl', 'generate_reports', 'manual__2025-10-11T11:32:15.420045+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/cafe_sales_etl_dag.py', '--cfg-path', '/tmp/tmp2snvz87j']
[2025-10-11T14:37:40.125+0300] {standard_task_runner.py:105} INFO - Job 55: Subtask generate_reports
[2025-10-11T14:37:40.173+0300] {task_command.py:467} INFO - Running <TaskInstance: cafe_sales_etl.generate_reports manual__2025-10-11T11:32:15.420045+00:00 [running]> on host archlinux
[2025-10-11T14:37:40.249+0300] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='cafe_sales_etl' AIRFLOW_CTX_TASK_ID='generate_reports' AIRFLOW_CTX_EXECUTION_DATE='2025-10-11T11:32:15.420045+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-11T11:32:15.420045+00:00'
[2025-10-11T14:37:40.250+0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-10-11T14:37:40.250+0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-10-11T14:37:40.250+0300] {logging_mixin.py:190} INFO - Current task name:generate_reports state:running start_date:2025-10-11 11:37:40.083569+00:00
[2025-10-11T14:37:40.250+0300] {logging_mixin.py:190} INFO - Dag name:cafe_sales_etl and current dag run status:running
[2025-10-11T14:37:40.251+0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-11T14:37:40.258+0300] {logging_mixin.py:190} WARNING - /home/hsooni/cafe_sales_etl/airflow/dags/cafe_sales_etl_dag.py:115 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-10-11T14:37:40.259+0300] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/airflow/dags/cafe_sales_etl_dag.py", line 115, in run_sql_reports
    df = pd.read_sql_query(text(query), engine)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 526, in read_sql_query
    return pandas_sql.read_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 2738, in read_query
    cursor = self.execute(sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 2670, in execute
    raise TypeError("Query must be a string unless using sqlalchemy.")
TypeError: Query must be a string unless using sqlalchemy.
[2025-10-11T14:37:40.267+0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-10-11T14:37:40.267+0300] {logging_mixin.py:190} INFO - Task start:2025-10-11 11:37:40.083569+00:00 end:2025-10-11 11:37:40.266612+00:00 duration:0.183043
[2025-10-11T14:37:40.267+0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): generate_reports> dag:<DAG: cafe_sales_etl> dagrun:<DagRun cafe_sales_etl @ 2025-10-11 11:32:15.420045+00:00: manual__2025-10-11T11:32:15.420045+00:00, state:running, queued_at: 2025-10-11 11:32:15.431733+00:00. externally triggered: True>
[2025-10-11T14:37:40.267+0300] {logging_mixin.py:190} INFO - Failure caused by Query must be a string unless using sqlalchemy.
[2025-10-11T14:37:40.268+0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=cafe_sales_etl, task_id=generate_reports, run_id=manual__2025-10-11T11:32:15.420045+00:00, execution_date=20251011T113215, start_date=20251011T113740, end_date=20251011T113740
[2025-10-11T14:37:40.287+0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-11T14:37:40.287+0300] {standard_task_runner.py:124} ERROR - Failed to execute job 55 for task generate_reports (Query must be a string unless using sqlalchemy.; 57862)
Traceback (most recent call last):
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/airflow/dags/cafe_sales_etl_dag.py", line 115, in run_sql_reports
    df = pd.read_sql_query(text(query), engine)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 526, in read_sql_query
    return pandas_sql.read_query(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 2738, in read_query
    cursor = self.execute(sql, params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsooni/cafe_sales_etl/venv/lib/python3.12/site-packages/pandas/io/sql.py", line 2670, in execute
    raise TypeError("Query must be a string unless using sqlalchemy.")
TypeError: Query must be a string unless using sqlalchemy.
[2025-10-11T14:37:40.297+0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-10-11T14:37:40.327+0300] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-11T14:37:40.328+0300] {local_task_job_runner.py:245} INFO - ::endgroup::
